---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ec2-user
  become: root
  become_method: sudo

  roles:
    - common
