---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all:!localhost
  remote_user: '{{ remote_user }}'
  become: yes
  become_method: sudo
  vars_files:
    - "vars/{{ deploy_method }}.yml"
  roles:
    - { role: ansiblebit.oracle-java,
      oracle_java_set_as_default: yes,
      oracle_java_version: 8,
      oracle_java_version_update: 131,
      oracle_java_version_build: 11,
      oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version }}u{{ oracle_java_version_update }}-b{{ oracle_java_version_build }}/d54c1d3a095b4ff2b6607d096fa80163/{{ oracle_java_rpm_filename }}"}
    - common
    - hadoop-common
    - hive
